[context.production.environment]
  HUGO_VERSION = "0.120.3"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.120.3"

[build]
  publish = "/public"
  command = "hugo --minify"
